// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgBWcUjBKoK63-psos1wNVzh3Z6NBKAGo',
    appId: '1:499415874093:web:5e5f9018df49d694aa96a4',
    messagingSenderId: '499415874093',
    projectId: 'flutter-task-9b86f',
    authDomain: 'flutter-task-9b86f.firebaseapp.com',
    storageBucket: 'flutter-task-9b86f.firebasestorage.app',
    measurementId: 'G-4CQLK2YLQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyqVee0h4RMfDbicoGzKKV7_SB5xbnE_8',
    appId: '1:499415874093:android:c615b754f3c40fcaaa96a4',
    messagingSenderId: '499415874093',
    projectId: 'flutter-task-9b86f',
    storageBucket: 'flutter-task-9b86f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaZINujJAnwe8k8osyDFBIjz2_dwVU5BI',
    appId: '1:499415874093:ios:ba39a7c810a2238faa96a4',
    messagingSenderId: '499415874093',
    projectId: 'flutter-task-9b86f',
    storageBucket: 'flutter-task-9b86f.firebasestorage.app',
    iosBundleId: 'com.example.flutterTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaZINujJAnwe8k8osyDFBIjz2_dwVU5BI',
    appId: '1:499415874093:ios:ba39a7c810a2238faa96a4',
    messagingSenderId: '499415874093',
    projectId: 'flutter-task-9b86f',
    storageBucket: 'flutter-task-9b86f.firebasestorage.app',
    iosBundleId: 'com.example.flutterTask',
  );
}
