on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

name: "Build & Release"

jobs:
  build:
    name: Build & Release
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Build Android APK
        run: flutter build apk --release --split-per-abi

      - name: Build iOS IPA
        run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload

      - name: Install Firebase CLI
        run: curl -sL https://firebase.tools | bash

      - name: Distribute Android APK to Firebase App Distribution
        run: |
          firebase appdistribution:distribute build/app/outputs/apk/release/app-arm64-v8a-release.apk \
            --app ${{ secrets.FIREBASE_APP_ID }} \
            --groups "testers" \
            --token ${{ secrets.FIREBASE_TOKEN }}

      - name: Distribute iOS IPA to Firebase App Distribution
        run: |
          firebase appdistribution:distribute build/ios/iphoneos/app.ipa \
            --app ${{ secrets.FIREBASE_IOS_APP_ID }} \
            --groups "testers" \
            --token ${{ secrets.FIREBASE_TOKEN }}

      - name: Push artifacts to GitHub Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            build/app/outputs/apk/release/*.apk
            build/ios/iphoneos/app.ipa
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
